import React from 'react';
import Navbar from '../../components/Navbar';
import Contact from '../../components/contact';
import Schedule from '../../components/Schedule';
import Link from 'next/link';

const PageSubmission: React.FC = () => {
  return (
    <>
    <div id="ourteam" className="bg-white">
    <Navbar />
    <div id='submission' className="text-white p-6 sm:pt-60 md:px-16 md:pt-12 lg:px-20 lg:pt-16 pt-10">
      <div className="md:pt-18 pt-10 ">
        <h2 className="md:text-5xl text-3xl font-bold text-[#CC5F00]">CVMI-2025 Paper Submission</h2>
        <div className="w-[50%] h-1 bg-[#CC5F00] mt-2"></div>
        </div>
      <div className="text-black font-roboto font-medium text-2xl leading-[48px] tracking-normal p-6 mt-">
        <h2 className="text-4xl font-bold mb-4 text-[#000] underline">
            Intstructions
        </h2>
        <div className="max-w-full">
          <p className="mb-4">
          Prospective authors are invited to submit full-length original research papers. In submitting a manuscript to IEEE CVMI 2025, authors acknowledge that no paper substantially similar in content has been or will be submitted to another journal, conference or workshop during the review period. In such a case the paper will be rejected without review. Papers must be electronically submitted before the deadline expires without exception.
          </p>
          <p className="mb-4">
          The paper must not exceed 6 pages in length (including all text, figures, and references). Two additional pages can be allowed at additional cost. The manuscript must be submitted in pdf format only and the file size of your manuscript should not exceed 10 MB.
          </p>
          <p className="mb-4">
          IEEE CVMI 2025 follows double blind review process. It means the identity of authors are not known to reviewers and vice-versa. Hence, Authors are required to remove the name and affiliation of authors from the paper. Authors should not refer any resources in the submitted paper that can lead to recognition of identity of authors.
          </p>
          <p className="mb-4">
          Use a proper tool to convert the resulting source into a pdf document that has only scalable fonts with all fonts embedded.
          </p>
          <p className="mb-4">
          The images embedded in the paper must not contain transparent pixels (i.e., an alpha-channel of a transparent color) since this could lead to problems when displaying or printing the pdf.The pdf manuscript must not have Adobe Document Protection or Document Security enabled.
          </p>
        </div>
      </div>
      <div className="text-black font-roboto font-medium text-2xl leading-[48px] tracking-normal p-6 mt-">
        <h2 className="text-4xl font-bold mb-4 text-[#000] underline">
        Guidelines for Artificial Intelligence (AI)-Generated Text:
        </h2>
        <div className="max-w-full">
          <p className="mb-4">
          The use of content generated by artificial intelligence (AI) in a paper (including but not limited to text, figures, images, and code) shall be disclosed in the acknowledgments section of any paper submitted to an IEEE publication. The AI system used shall be identified, and specific sections of the paper that use AI-generated content shall be identified and accompanied by a brief explanation regarding the level at which the AI system was used to generate the content.
          </p>
          <p className="mb-4">
          The use of AI systems for editing and grammar enhancement is common practice and, as such, is generally outside the intent of the above policy. In this case, disclosure as noted above is recommended.
          </p>
        </div>
      </div>
      <div className="text-black font-roboto font-medium text-2xl leading-[48px] tracking-normal p-6 mt-">
        <h2 className="text-4xl font-bold mb-4 text-[#000] underline">
        Guidelines for Plagiarism:
        </h2>
        <div className="max-w-full">
          <p className="mb-4">
          In accordance with the IEEE policy, plagiarism in any form, at any level, is unacceptable. Therefore, the conference reserves the right to reject the final manuscript which is found to have high degree of plagiarism after registration without refund.
          </p>
        </div>
      </div>
      <div className="text-black font-roboto font-medium text-2xl leading-[48px] tracking-normal p-6 mt-">
        <h2 className="text-4xl font-bold mb-4 text-[#000] underline">
        Proceedings:
        </h2>
        <div className="max-w-full">
          <p className="mb-4">
          The proceedings of the conference will be published by IEEE Xplore.
          </p>
        </div>
      </div>
      <div className="text-black font-roboto font-medium text-2xl leading-[48px] tracking-normal p-6 mt-">
        <h2 className="text-4xl font-bold mb-4 text-[#000] underline">
        Preparing your proceedings paper:
        </h2>
        <div className="max-w-full">
          <p className="">
          In accordance with the IEEE policy, plagiarism in any form, at any level, is unacceptable. Therefore, the conference reserves the right to reject the final manuscript which is found to have high degree of plagiarism after registration without refund.
          </p>
          <Link href={"https://www.ieee.org/conferences/publishing/templates.html"} className="text-blue-500 underline mb-8">
          Proceedings Guidelines for Authors
          </Link>
          <p className="">
          Authors must use the manuscript template specified here. 
          </p>
          <Link href={"https://cvmi2024.iiita.ac.in/files/latex_cvmi2024.zip"} className="text-blue-500 block underline">
          LaTeX Template
          </Link>
          <Link href={"https://cvmi2024.iiita.ac.in/files/word_cvmi2024.zip"} className="text-blue-500 underline mb-8">
          Word Template
          </Link>
        </div>
      </div>
      <div className="text-black font-roboto font-medium text-2xl leading-[48px] tracking-normal p-6 mt-">
        <h2 className="text-4xl font-bold mb-4 text-[#000] underline">
        Instruction for uploading manuscripts:
        </h2>
        <div className="max-w-full">
          <p className="mb-4">
          The manuscript has to be uploaded online at the CVMI2025 Microsoft Research paper submission portal CMT.          </p>
        </div>
      </div>
    </div>
    <Schedule/>
    <Contact/>
    </div>
    </>
  );
};

export default PageSubmission;