import './globals.css';
import type { Metadata } from 'next';
import { Inter} from 'next/font/google';
import { Analytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'IEEE CVMI 2025',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className + 'bg-transparent antialiased'}suppressHydrationWarning>
        <main className="">
          {children}
          <Analytics/>
          <SpeedInsights/>
        </main>
      </body>
    </html>
  );
}