import React from 'react';
import Navbar from '../../components/Navbar';
import Contact from '../../components/contact';
import Link from 'next/link';

const FinalSubmissionGuidelines: React.FC = () => {
  return (
    <>
      <div id="finalsubmission" className="bg-white">
        <Navbar />
        <div className="text-white p-6 sm:pt-60 md:px-16 md:pt-12 lg:px-20 lg:pt-16 pt-10">
          <div className="md:pt-18 pt-6 mb-5">
            <h2 className="md:text-5xl text-3xl font-bold text-[#CC5F00] underline">Final Paper Submission Guidelines</h2>
        </div>
          {/* Important Note */}
          <div className="text-black font-roboto font-medium text-lg leading-relaxed mb-8">
            <p className="mb-4">
              Please note that the <strong>last date for uploading final camera ready manuscript is September 25, 2025.</strong>
            </p>
            <p className="mb-6">
              At least one author must complete registration before uploading the final manuscript. See the{' '}
              <Link href="/registration" className="text-blue-500 underline hover:text-blue-700">
                Registration Page
              </Link>{' '}
              for details.
            </p>
          </div>

          <div className="text-black font-roboto font-medium text-lg leading-relaxed mb-8">
            <h2 className="text-3xl font-bold mb-6 text-[#000000]">
              1. Preparation of Camera Ready Manuscript
            </h2>
            
            <div className="space-y-6">
              <div>
                <h3 className="text-xl font-bold mb-3 text-[#000000]">IEEE Template:</h3>
                <p className="mb-4">
                  Authors are requested to prepare their manuscripts using the official IEEE conference template.  
                  The templates can be downloaded for&nbsp; 
                  <Link href="https://cvmi2024.iiita.ac.in/files/latex_cvmi2024.zip" className="text-blue-500 underline hover:text-blue-700">LaTeX</Link> or <Link href="https://cvmi2024.iiita.ac.in/files/word_cvmi2024.zip" className="text-blue-500 underline hover:text-blue-700">Word</Link>.
                  Use the A4 format. DO NOT use the US Letter format and do not paginate your paper. The final manuscript should adhere to page length, 
                  i.e. 6 pages in IEEE format. Upto two more pages can be considered with extra page length charge.
                </p>
              </div>

              <div> 
                <h3 className="text-xl font-bold mb-3 text-[#000000]">IEEE Submission Policy:</h3>
                <p className="mb-4">
                  Authors are required to follow the IEEE Conference Submission Policy very strictly available{' '}
                  <Link href="https://conferences.ieeeauthorcenter.ieee.org/author-ethics/guidelines-and-policies/submission-policies/" className="text-blue-500 underline hover:text-blue-700">here</Link>. 
                  The manuscript can be withdrawn from the proceedings at any stage in the negligence of the IEEE Policy.
                </p>
              </div>

              <div>
                <h3 className="text-xl font-bold mb-3 text-[#000000]">Guidelines for Artificial Intelligence (AI)-Generated Text:</h3>
                <p className="mb-4">
                  The use of content generated by artificial intelligence (AI) in a paper (including but not limited to text, figures, images, and code) 
                  shall be disclosed in the acknowledgments section of any paper submitted to an IEEE publication. The AI system used shall be identified, 
                  and specific sections of the paper that use AI-generated content shall be identified and accompanied by a brief explanation regarding 
                  the level at which the AI system was used to generate the content.
                </p>
                <p className="mb-4">
                  The use of AI systems for editing and grammar enhancement is common practice and, as such, is generally outside the intent of the above policy. 
                  In this case, disclosure as noted above is recommended.
                </p>
              </div>

              <div>
                <h3 className="text-xl font-bold mb-3 text-[#000000]">Guidelines for Plagiarism:</h3>
                <p className="mb-4">
                  In accordance with the IEEE policy, plagiarism in any form, at any level, is unacceptable. Therefore, the conference reserves the right 
                  to reject the final manuscript which is found to have high degree of plagiarism after registration without refund.
                </p>
              </div>
            </div>
          </div>

          {/* Incorporation of Reviewer's Comments */}
          <div className="text-black font-roboto font-medium text-lg leading-relaxed mb-8">
            <h3 className="text-xl font-bold mb-3 text-[#000000]">Incorporation of Reviewer's Comments:</h3>
            <p className="mb-4">
              Update your manuscript as per REVIEWERS' COMMENTS, which are intended to improve the quality of your paper before the final publication. 
              The listed comments should be addressed carefully in your revision, it is mandatory for all authors to incorporate all the changes 
              suggested by reviewers and adhere to IEEE conditions, else their paper will be excluded from conference proceedings. A response to reviewer 
              comments is also required to be submitted with response for each comment and how and where it is incorporated in the final manuscript.
            </p>
          </div>

          {/* Section 2: Validate Your Camera Ready Manuscript */}
          <div className="text-black font-roboto font-medium text-lg leading-relaxed mb-8">
            <h2 className="text-3xl font-bold mb-6 text-[#000000]">
              2. Validate Your Camera Ready Manuscript Using IEEE PDF eXpress
            </h2>

            {/* Three-column layout for different user types */}
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-8">
              
              {/* First-time users */}
              <div className="bg-gray-50 p-6 rounded-lg">
                <h3 className="text-xl font-bold mb-4 text-[#000000]">First-time users</h3>
                <div className="space-y-4">
                  <p><strong>a.</strong> Click "New Users - Click Here".</p>
                  <p><strong>b.</strong> Enter 66673X as the Conference ID, your email address, and choose a new password. Continue to enter information as prompted.</p>
                  <p><strong>c.</strong> An Online confirmation will be displayed, and an email confirmation will be sent verifying your account setup.</p>
                </div>
              </div>

              {/* Previous users */}
              <div className="bg-gray-50 p-6 rounded-lg">
                <h3 className="text-xl font-bold mb-4 text-[#000000]">Previous users, but using it the first time for IEEE CVMI 2025</h3>
                <div className="space-y-4">
                  <p><strong>a.</strong> Enter 66673X as the Conference ID, your email address, and enter the password you used for your old account.</p>
                  <p><strong>b.</strong> When you click "Login", you'll receive an error saying you need to set up an account. Simply click "Continue". By entering your previously used email address and password combination, you will enable your old account for access to this new conference.</p>
                  <p><strong>c.</strong> Check that the contact information is still valid and click "Submit".</p>
                  <p><strong>d.</strong> You will receive online and email confirmation of successful account setup.</p>
                </div>
              </div>

              {/* Returning users */}
              <div className="bg-gray-50 p-6 rounded-lg">
                <h3 className="text-xl font-bold mb-4 text-[#000000]">Returning users</h3>
                <div className="space-y-4">
                  <p><strong>a.</strong> Enter 66673X as the Conference ID, email address and password.</p>
                </div>
              </div>
            </div>

            {/* Additional instructions */}
            <div className="space-y-4 mb-8">
              <p>Before creating PDF, proofread tex or doc file thoroughly to confirm that it requires no revision.</p>
              <p>
                Access the{' '}
                <Link href="https://ieee-pdf-express.org/" className="text-blue-500 underline hover:text-blue-700">
                  IEEE PDF eXpress Plus site
                </Link>.
              </p>
              <p>For each conference paper, click "Create New Title".</p>
              <p>Enter identifying text for the paper (title is recommended but not required).</p>
              <p>Click "Submit PDF for Checking".</p>
              <p>Click Browse and navigate to file, and click "Upload File". You will receive online and email confirmation of successful upload.</p>
              <p>
                You will receive an email with your checked PDF or IEEE PDF eXpress Plus-converted PDF attached. If you submitted a PDF for Checking, 
                the email will show if your file passed or failed.
              </p>
              <p>In case of "fail", make changes in paper according to the PDF express report and revalidate.</p>
            </div>
          </div>

          {/* Section 3: Submission of Camera Ready Manuscripts */}
          <div className="text-black font-roboto font-medium text-lg leading-relaxed mb-8">
            <h2 className="text-3xl font-bold mb-6 text-[#000000]">
              3. Submission of Camera Ready Manuscripts and IEEE eCopyright Form to IEEE CVMI 2025
            </h2>

            <div className="space-y-6">
              <div>
                <p>
                  <strong>Step 1:</strong> Login to Microsoft CMT as an author of IEEE CVMI 2025 (
                  <Link href="https://cmt3.research.microsoft.com/CVMIconf2025" className="text-blue-500 underline hover:text-blue-700">here</Link>) 
                  and click the link to submit the eCopyright form. Then follow the on-screen instructions. Note that the title, 
                  list of authors and order of authors in the portal as well as in the paper pdf must be same as in the copyright form. 
                  In case of any mismatch, first edit your submission in the portal and then submit the copyright form.
                </p>
              </div>

              <div>
                <p>
                  <strong>Step 2:</strong> From the Author Console in CMT, click on the link 'Create Camera Ready Submission'. Submit the IEEE PDF eXpress 
                  verified paper (as XXX.pdf), duly signed copyright form downloaded from IEEE (as XXX-CR.pdf), response to reviewer comments 
                  (as XXX-RRC.pdf) and Source Editable (Word/LaTeX format) file of Camera Ready Copy (in Zip folder) with all supporting files 
                  (as XXX.zip). Please note that XXX is the three-digit paper ID (zero-appended if necessary, for example XXX for paper id 5 will be 005).
                </p>
              </div>

              <div>
                <p>
                  <strong>Step 3:</strong> For detailed instructions on how to submit IEEE eCopyright form and Camera-Ready Copy on Microsoft CMT,{' '}
                  <Link href="https://cmt3.research.microsoft.com/docs/help/author/camera-ready-submission.html#ieee-copyright" className="text-blue-500 underline hover:text-blue-700">click here</Link>.
                </p>
              </div>

              <div>
                <p>
                  <strong>Step 4:</strong> Click the "Submit" button or "Save changes" button if you're editing a previous submission—at the bottom 
                  of the page to save all your changes. Unless you press the "Submit"/"Save changes" button, any changes you've made to the 
                  camera-ready submission (including file uploads and changes to the title, abstract, and author list) will not be saved.
                </p>
              </div>
            </div>
          </div>
        </div>
        <Contact />
      </div>
    </>
  );
};

export default FinalSubmissionGuidelines;
